function KLT_plotFcn_All(app, absDistance, QuadraticVelocity, cubicVelocity, froudeVelocity, missingInd)

    f1 = figure(); hold on;
    ax1 = gca;
    grid off
    set(ax1,'TickLabelInterpreter','latex')
    
    velocityIn = QuadraticVelocity;
    h(1)       = plot( absDistance, velocityIn, 'k-' );
    h(2)       = scatter( absDistance, velocityIn,...
        '*', ...
        'MarkerEdgeColor', 'k',...
        'MarkerFaceColor', 'k');
    h(3)        = scatter( absDistance(missingInd), velocityIn(missingInd),...
        'o',...
        'MarkerEdgeColor', 'k',...
        'MarkerFaceColor', 'k');
    
    velocityIn = cubicVelocity;
    h(4)        = plot( absDistance, velocityIn, 'r-' );
    h(5)        = scatter( absDistance, velocityIn,...
        '*', ...
        'MarkerEdgeColor', 'r',...
        'MarkerFaceColor', 'r');
    h(6)        = scatter( absDistance(missingInd), velocityIn(missingInd),...
        'o',...
        'MarkerEdgeColor', 'r',...
        'MarkerFaceColor', 'r');
   
    velocityIn = froudeVelocity;
    h(7)        = plot( absDistance, velocityIn, 'b-' );
    h(8)        = scatter( absDistance, velocityIn,...
        '*', ...
        'MarkerEdgeColor', 'b',...
        'MarkerFaceColor', 'b');
    h(9)        = scatter( absDistance(missingInd), velocityIn(missingInd),...
        'o',...
        'MarkerEdgeColor', 'b',...
        'MarkerFaceColor', 'b');
      
    
    xlabel(['Cross-section location $\mathrm{(m)}$'] , 'Interpreter','LaTex');
    ylabel(['Velocity $\mathrm{(m \ s^{-1})}$ '] , 'Interpreter','LaTex');
    set(ax1,'fontsize',14)

    legend(h([1,4,7]), 'Quadratic', 'Cubic', 'Froude',...
        'Interpreter','LaTex');
       
if strcmp (app.ProcessingModeDropDown.Value, 'Multiple Videos') == true
    try
        temp1 = [app.directory_save_multiple '\crossSectionVelocity.png'];
        saveas(f1,temp1,'png')
        cla (ax1);
        reset(gcf);
        reset(gca);
        close (f1)
        waitfor(f1)
    catch
    end
end

end